# Generated by Django 6.0.4 on 2026-04-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lote', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_expiracion', models.DateField()),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
    ]
