# Generated by Django 6.0.4 on 2026-06-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor_usuario_remove_medicamento_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='categoria',
            field=models.CharField(choices=[('analgesico', 'Analgésico'), ('antiinflamatorio', 'Antiinflamatorio'), ('antibiotico', 'Antibiótico'), ('antihipertensivo', 'Antihipertensivo'), ('antidiabético', 'Antidiabético'), ('vitamina', 'Vitamina / Suplemento'), ('antihistaminico', 'Antihistamínico'), ('gastrointestinal', 'Gastrointestinal'), ('dermatologico', 'Dermatológico'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
